steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/harvit-training', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/harvit-training']

  # Deploy to Cloud Run (with GPU)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'compute'
    - 'instances'
    - 'create-with-container'
    - 'harvit-training-instance'
    - '--container-image'
    - 'gcr.io/$PROJECT_ID/harvit-training'
    - '--zone'
    - 'us-central1-a'
    - '--machine-type'
    - 'n1-standard-8'
    - '--accelerator'
    - 'type=nvidia-tesla-t4,count=1'
    - '--maintenance-policy'
    - 'TERMINATE'
    - '--boot-disk-size'
    - '50GB'
    - '--metadata-from-file'
    - 'startup-script=startup.sh'

images:
  - 'gcr.io/$PROJECT_ID/harvit-training' 